name: flutter_showdown
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  html: ^0.14.0+4
  image: ^2.1.18
  provider: ^4.3.2+2
  super_enum: ^0.4.2
  url_launcher: ^5.7.8
  webview_flutter: ^1.0.5
  web_socket_channel: ^1.1.0
  speech_to_text: ^2.7.0
  cached_network_image: ^2.3.3
  json_annotation: ^3.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  super_enum_generator: ^0.5.0
  build_runner: ^1.7.1
  json_serializable: ^3.5.0
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/icons/appstore.png"
  image_path_android: "assets/icons/playstore.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/abilities.json
    - assets/data/learnset.json
    - assets/data/moves.json
    - assets/data/pokedex.json
    - assets/pokemon-icons/
    - assets/types/
    - assets/icons/pokemonshowdownbeta.png
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf