const String AVATARLINKPREFIX =
    'https://play.pokemonshowdown.com/sprites/trainers/';
const String CUSTOMAVATARLINKPREFIX =
    'https://play.pokemonshowdown.com/sprites/trainers-custom/';

//https://github.com/smogon/pokemon-showdown-client/blob/master/website/pages/staff.md
const Map<String, String> GROUPS = {
  '~': 'Administrator (~)',
  '#': 'Room Owner (#)',
  '&': 'Administrator (&)',
  '★': 'Host (★)',
  '@': 'Moderator (@)',
  '%': 'Driver (%)',
  '^': '^', // TODO(anyone): find the name of this group
  '*': 'Bot (*)',
  '☆': 'Player (☆)',
  '+': 'Voice (+)',
  ' ': '',
  '!': 'Muted (!)',
  '✖': 'Namelocked (✖)',
  '‽': 'Locked (‽)'
};

//https://github.com/smogon/pokemon-showdown-client/blob/f1252eed1f23d67a2fa7a0e67cccd9e5b98e9b80/src/battle-dex-data.ts#L619
const Map<String, String> BATTLEAVATARNUMBERS = {
  '1': 'lucas',
  '2': 'dawn',
  '3': 'youngster-gen4',
  '4': 'lass-gen4dp',
  '5': 'camper',
  '6': 'picnicker',
  '7': 'bugcatcher',
  '8': 'aromalady',
  '9': 'twins-gen4dp',
  '10': 'hiker-gen4',
  '11': 'battlegirl-gen4',
  '12': 'fisherman-gen4',
  '13': 'cyclist-gen4',
  '14': 'cyclistf-gen4',
  '15': 'blackbelt-gen4dp',
  '16': 'artist-gen4',
  '17': 'pokemonbreeder-gen4',
  '18': 'pokemonbreederf-gen4',
  '19': 'cowgirl',
  '20': 'jogger',
  '21': 'pokefan-gen4',
  '22': 'pokefanf-gen4',
  '23': 'pokekid',
  '24': 'youngcouple-gen4dp',
  '25': 'acetrainer-gen4dp',
  '26': 'acetrainerf-gen4dp',
  '27': 'waitress-gen4',
  '28': 'veteran-gen4',
  '29': 'ninjaboy',
  '30': 'dragontamer',
  '31': 'birdkeeper-gen4dp',
  '32': 'doubleteam',
  '33': 'richboy-gen4',
  '34': 'lady-gen4',
  '35': 'gentleman-gen4dp',
  '36': 'madame-gen4dp',
  '37': 'beauty-gen4dp',
  '38': 'collector',
  '39': 'policeman-gen4',
  '40': 'pokemonranger-gen4',
  '41': 'pokemonrangerf-gen4',
  '42': 'scientist-gen4dp',
  '43': 'swimmer-gen4dp',
  '44': 'swimmerf-gen4dp',
  '45': 'tuber',
  '46': 'tuberf',
  '47': 'sailor',
  '48': 'sisandbro',
  '49': 'ruinmaniac',
  '50': 'psychic-gen4',
  '51': 'psychicf-gen4',
  '52': 'gambler',
  '53': 'guitarist-gen4',
  '54': 'acetrainersnow',
  '55': 'acetrainersnowf',
  '56': 'skier',
  '57': 'skierf-gen4dp',
  '58': 'roughneck-gen4',
  '59': 'clown',
  '60': 'worker-gen4',
  '61': 'schoolkid-gen4dp',
  '62': 'schoolkidf-gen4',
  '63': 'roark',
  '64': 'barry',
  '65': 'byron',
  '66': 'aaron',
  '67': 'bertha',
  '68': 'flint',
  '69': 'lucian',
  '70': 'cynthia-gen4',
  '71': 'bellepa',
  '72': 'rancher',
  '73': 'mars',
  '74': 'galacticgrunt',
  '75': 'gardenia',
  '76': 'crasherwake',
  '77': 'maylene',
  '78': 'fantina',
  '79': 'candice',
  '80': 'volkner',
  '81': 'parasollady-gen4',
  '82': 'waiter-gen4dp',
  '83': 'interviewers',
  '84': 'cameraman',
  '85': 'reporter',
  '86': 'idol',
  '87': 'cyrus',
  '88': 'jupiter',
  '89': 'saturn',
  '90': 'galacticgruntf',
  '91': 'argenta',
  '92': 'palmer',
  '93': 'thorton',
  '94': 'buck',
  '95': 'darach',
  '96': 'marley',
  '97': 'mira',
  '98': 'cheryl',
  '99': 'riley',
  '100': 'dahlia',
  '101': 'ethan',
  '102': 'lyra',
  '103': 'twins-gen4',
  '104': 'lass-gen4',
  '105': 'acetrainer-gen4',
  '106': 'acetrainerf-gen4',
  '107': 'juggler',
  '108': 'sage',
  '109': 'li',
  '110': 'gentleman-gen4',
  '111': 'teacher',
  '112': 'beauty',
  '113': 'birdkeeper',
  '114': 'swimmer-gen4',
  '115': 'swimmerf-gen4',
  '116': 'kimonogirl',
  '117': 'scientist-gen4',
  '118': 'acetrainercouple',
  '119': 'youngcouple',
  '120': 'supernerd',
  '121': 'medium',
  '122': 'schoolkid-gen4',
  '123': 'blackbelt-gen4',
  '124': 'pokemaniac',
  '125': 'firebreather',
  '126': 'burglar',
  '127': 'biker-gen4',
  '128': 'skierf',
  '129': 'boarder',
  '130': 'rocketgrunt',
  '131': 'rocketgruntf',
  '132': 'archer',
  '133': 'ariana',
  '134': 'proton',
  '135': 'petrel',
  '136': 'eusine',
  '137': 'lucas-gen4pt',
  '138': 'dawn-gen4pt',
  '139': 'madame-gen4',
  '140': 'waiter-gen4',
  '141': 'falkner',
  '142': 'bugsy',
  '143': 'whitney',
  '144': 'morty',
  '145': 'chuck',
  '146': 'jasmine',
  '147': 'pryce',
  '148': 'clair',
  '149': 'will',
  '150': 'koga',
  '151': 'bruno',
  '152': 'karen',
  '153': 'lance',
  '154': 'brock',
  '155': 'misty',
  '156': 'ltsurge',
  '157': 'erika',
  '158': 'janine',
  '159': 'sabrina',
  '160': 'blaine',
  '161': 'blue',
  '162': 'red',
  '163': 'red',
  '164': 'silver',
  '165': 'giovanni',
  '166': 'unknownf',
  '167': 'unknown',
  '168': 'unknown',
  '169': 'hilbert',
  '170': 'hilda',
  '171': 'youngster',
  '172': 'lass',
  '173': 'schoolkid',
  '174': 'schoolkidf',
  '175': 'smasher',
  '176': 'linebacker',
  '177': 'waiter',
  '178': 'waitress',
  '179': 'chili',
  '180': 'cilan',
  '181': 'cress',
  '182': 'nurseryaide',
  '183': 'preschoolerf',
  '184': 'preschooler',
  '185': 'twins',
  '186': 'pokemonbreeder',
  '187': 'pokemonbreederf',
  '188': 'lenora',
  '189': 'burgh',
  '190': 'elesa',
  '191': 'clay',
  '192': 'skyla',
  '193': 'pokemonranger',
  '194': 'pokemonrangerf',
  '195': 'worker',
  '196': 'backpacker',
  '197': 'backpackerf',
  '198': 'fisherman',
  '199': 'musician',
  '200': 'dancer',
  '201': 'harlequin',
  '202': 'artist',
  '203': 'baker',
  '204': 'psychic',
  '205': 'psychicf',
  '206': 'cheren',
  '207': 'bianca',
  '208': 'plasmagrunt-gen5bw',
  '209': 'n',
  '210': 'richboy',
  '211': 'lady',
  '212': 'pilot',
  '213': 'workerice',
  '214': 'hoopster',
  '215': 'scientistf',
  '216': 'clerkf',
  '217': 'acetrainerf',
  '218': 'acetrainer',
  '219': 'blackbelt',
  '220': 'scientist',
  '221': 'striker',
  '222': 'brycen',
  '223': 'iris',
  '224': 'drayden',
  '225': 'roughneck',
  '226': 'janitor',
  '227': 'pokefan',
  '228': 'pokefanf',
  '229': 'doctor',
  '230': 'nurse',
  '231': 'hooligans',
  '232': 'battlegirl',
  '233': 'parasollady',
  '234': 'clerk',
  '235': 'clerk-boss',
  '236': 'backers',
  '237': 'backersf',
  '238': 'veteran',
  '239': 'veteranf',
  '240': 'biker',
  '241': 'infielder',
  '242': 'hiker',
  '243': 'madame',
  '244': 'gentleman',
  '245': 'plasmagruntf-gen5bw',
  '246': 'shauntal',
  '247': 'marshal',
  '248': 'grimsley',
  '249': 'caitlin',
  '250': 'ghetsis-gen5bw',
  '251': 'depotagent',
  '252': 'swimmer',
  '253': 'swimmerf',
  '254': 'policeman',
  '255': 'maid',
  '256': 'ingo',
  '257': 'alder',
  '258': 'cyclist',
  '259': 'cyclistf',
  '260': 'cynthia',
  '261': 'emmet',
  '262': 'hilbert-dueldisk',
  '263': 'hilda-dueldisk',
  '264': 'hugh',
  '265': 'rosa',
  '266': 'nate',
  '267': 'colress',
  '268': 'beauty-gen5bw2',
  '269': 'ghetsis',
  '270': 'plasmagrunt',
  '271': 'plasmagruntf',
  '272': 'iris-gen5bw2',
  '273': 'brycenman',
  '274': 'shadowtriad',
  '275': 'rood',
  '276': 'zinzolin',
  '277': 'cheren-gen5bw2',
  '278': 'marlon',
  '279': 'roxie',
  '280': 'roxanne',
  '281': 'brawly',
  '282': 'wattson',
  '283': 'flannery',
  '284': 'norman',
  '285': 'winona',
  '286': 'tate',
  '287': 'liza',
  '288': 'juan',
  '289': 'guitarist',
  '290': 'steven',
  '291': 'wallace',
  '292': 'bellelba',
  '293': 'benga',
  '294': 'ash',
  '#bw2elesa': 'elesa-gen5bw2',
  '#teamrocket': 'teamrocket',
  '#yellow': 'yellow',
  '#zinnia': 'zinnia',
  '#clemont': 'clemont',
  '#wally': 'wally',
  'breeder': 'pokemonbreeder',
  'breederf': 'pokemonbreederf',
  '1001': '#1001',
  '1002': '#1002',
  '1003': '#1003',
  '1005': '#1005',
  '1010': '#1010',
};

//https://play.pokemonshowdown.com/sprites/trainers/
const List<String> AVATARSAVAILABLE = [
  'aaron',
  'aaron',
  'acerola',
  'acerola',
  'acetrainer-gen1',
  'acetrainer-gen1',
  'acetrainer-gen1rb',
  'acetrainer-gen1rb',
  'acetrainer-gen2',
  'acetrainer-gen2',
  'acetrainer-gen3',
  'acetrainer-gen3',
  'acetrainer-gen3jp',
  'acetrainer-gen3jp',
  'acetrainer-gen3rs',
  'acetrainer-gen3rs',
  'acetrainer-gen4',
  'acetrainer-gen4',
  'acetrainer-gen4dp',
  'acetrainer-gen4dp',
  'acetrainer',
  'acetrainer',
  'acetrainercouple-gen3',
  'acetrainercouple-gen3',
  'acetrainercouple',
  'acetrainercouple',
  'acetrainerf-gen1',
  'acetrainerf-gen1',
  'acetrainerf-gen1rb',
  'acetrainerf-gen1rb',
  'acetrainerf-gen2',
  'acetrainerf-gen2',
  'acetrainerf-gen3',
  'acetrainerf-gen3',
  'acetrainerf-gen3rs',
  'acetrainerf-gen3rs',
  'acetrainerf-gen4',
  'acetrainerf-gen4',
  'acetrainerf-gen4dp',
  'acetrainerf-gen4dp',
  'acetrainerf',
  'acetrainerf',
  'acetrainersnow',
  'acetrainersnow',
  'acetrainersnowf',
  'acetrainersnowf',
  'aetheremployee',
  'aetheremployee',
  'aetheremployeef',
  'aetheremployeef',
  'aetherfoundation',
  'aetherfoundation',
  'aetherfoundationf',
  'aetherfoundationf',
  'agatha-gen1',
  'agatha-gen1',
  'agatha-gen1rb',
  'agatha-gen1rb',
  'agatha-gen3',
  'agatha-gen3',
  'alder',
  'alder',
  'anabel-gen3',
  'anabel-gen3',
  'anabel',
  'anabel',
  'archer',
  'archer',
  'archie-gen3',
  'archie-gen3',
  'argenta',
  'argenta',
  'ariana',
  'ariana',
  'aromalady-gen3',
  'aromalady-gen3',
  'aromalady-gen3rs',
  'aromalady-gen3rs',
  'aromalady',
  'aromalady',
  'artist-gen4',
  'artist-gen4',
  'artist',
  'artist',
  'ash-alola',
  'ash-alola',
  'ash-capbackward',
  'ash-capbackward',
  'ash-hoenn',
  'ash-hoenn',
  'ash-johto',
  'ash-johto',
  'ash-kalos',
  'ash-kalos',
  'ash-sinnoh',
  'ash-sinnoh',
  'ash-unova',
  'ash-unova',
  'ash',
  'ash',
  'az',
  'az',
  'backers',
  'backers',
  'backersf',
  'backersf',
  'backpacker',
  'backpacker',
  'backpackerf',
  'backpackerf',
  'baker',
  'baker',
  'barry',
  'barry',
  'battlegirl-gen3',
  'battlegirl-gen3',
  'battlegirl-gen4',
  'battlegirl-gen4',
  'battlegirl',
  'battlegirl',
  'beauty-gen1',
  'beauty-gen1',
  'beauty-gen1rb',
  'beauty-gen1rb',
  'beauty-gen2',
  'beauty-gen2',
  'beauty-gen2jp',
  'beauty-gen2jp',
  'beauty-gen3',
  'beauty-gen3',
  'beauty-gen3rs',
  'beauty-gen3rs',
  'beauty-gen4dp',
  'beauty-gen4dp',
  'beauty-gen5bw2',
  'beauty-gen5bw2',
  'beauty-gen7',
  'beauty-gen7',
  'beauty',
  'beauty',
  'bellelba',
  'bellelba',
  'bellepa',
  'bellepa',
  'benga',
  'benga',
  'bertha',
  'bertha',
  'bianca-pwt',
  'bianca-pwt',
  'bianca',
  'bianca',
  'biker-gen1',
  'biker-gen1',
  'biker-gen1rb',
  'biker-gen1rb',
  'biker-gen2',
  'biker-gen2',
  'biker-gen3',
  'biker-gen3',
  'biker-gen4',
  'biker-gen4',
  'biker',
  'biker',
  'bill-gen3',
  'bill-gen3',
  'birch-gen3',
  'birch-gen3',
  'birdkeeper-gen1',
  'birdkeeper-gen1',
  'birdkeeper-gen1rb',
  'birdkeeper-gen1rb',
  'birdkeeper-gen2',
  'birdkeeper-gen2',
  'birdkeeper-gen3',
  'birdkeeper-gen3',
  'birdkeeper-gen3rs',
  'birdkeeper-gen3rs',
  'birdkeeper-gen4dp',
  'birdkeeper-gen4dp',
  'birdkeeper',
  'birdkeeper',
  'blackbelt-gen1',
  'blackbelt-gen1',
  'blackbelt-gen1rb',
  'blackbelt-gen1rb',
  'blackbelt-gen2',
  'blackbelt-gen2',
  'blackbelt-gen3',
  'blackbelt-gen3',
  'blackbelt-gen3rs',
  'blackbelt-gen3rs',
  'blackbelt-gen4',
  'blackbelt-gen4',
  'blackbelt-gen4dp',
  'blackbelt-gen4dp',
  'blackbelt',
  'blackbelt',
  'blaine-gen1',
  'blaine-gen1',
  'blaine-gen1rb',
  'blaine-gen1rb',
  'blaine-gen2',
  'blaine-gen2',
  'blaine-gen3',
  'blaine-gen3',
  'blaine',
  'blaine',
  'blue-gen1',
  'blue-gen1',
  'blue-gen1champion',
  'blue-gen1champion',
  'blue-gen1rb',
  'blue-gen1rb',
  'blue-gen1rbchampion',
  'blue-gen1rbchampion',
  'blue-gen1rbtwo',
  'blue-gen1rbtwo',
  'blue-gen1two',
  'blue-gen1two',
  'blue-gen2',
  'blue-gen2',
  'blue-gen3',
  'blue-gen3',
  'blue-gen3champion',
  'blue-gen3champion',
  'blue-gen3two',
  'blue-gen3two',
  'blue-gen7',
  'blue-gen7',
  'blue',
  'blue',
  'boarder-gen2',
  'boarder-gen2',
  'boarder',
  'boarder',
  'brandon-gen3',
  'brandon-gen3',
  'brawly-gen3',
  'brawly-gen3',
  'brawly-gen6',
  'brawly-gen6',
  'brawly',
  'brawly',
  'brendan-gen3',
  'brendan-gen3',
  'brendan-gen3rs',
  'brendan-gen3rs',
  'brock-gen1',
  'brock-gen1',
  'brock-gen1rb',
  'brock-gen1rb',
  'brock-gen2',
  'brock-gen2',
  'brock-gen3',
  'brock-gen3',
  'brock',
  'brock',
  'bruno-gen1',
  'bruno-gen1',
  'bruno-gen1rb',
  'bruno-gen1rb',
  'bruno-gen2',
  'bruno-gen2',
  'bruno-gen3',
  'bruno-gen3',
  'bruno',
  'bruno',
  'brycen',
  'brycen',
  'brycenman',
  'brycenman',
  'bryony',
  'bryony',
  'buck',
  'buck',
  'bugcatcher-gen1',
  'bugcatcher-gen1',
  'bugcatcher-gen1rb',
  'bugcatcher-gen1rb',
  'bugcatcher-gen2',
  'bugcatcher-gen2',
  'bugcatcher-gen3',
  'bugcatcher-gen3',
  'bugcatcher-gen3rs',
  'bugcatcher-gen3rs',
  'bugcatcher',
  'bugcatcher',
  'bugmaniac-gen3',
  'bugmaniac-gen3',
  'bugsy-gen2',
  'bugsy-gen2',
  'bugsy',
  'bugsy',
  'burgh',
  'burgh',
  'burglar-gen1',
  'burglar-gen1',
  'burglar-gen1rb',
  'burglar-gen1rb',
  'burglar-gen2',
  'burglar-gen2',
  'burglar-gen3',
  'burglar-gen3',
  'burglar',
  'burglar',
  'burnet',
  'burnet',
  'byron',
  'byron',
  'caitlin',
  'caitlin',
  'cameraman',
  'cameraman',
  'camper-gen2',
  'camper-gen2',
  'camper-gen3',
  'camper-gen3',
  'camper-gen3rs',
  'camper-gen3rs',
  'camper',
  'camper',
  'candice',
  'candice',
  'channeler-gen1',
  'channeler-gen1',
  'channeler-gen1rb',
  'channeler-gen1rb',
  'channeler-gen3',
  'channeler-gen3',
  'cheren-gen5bw2',
  'cheren-gen5bw2',
  'cheren',
  'cheren',
  'cheryl',
  'cheryl',
  'chili',
  'chili',
  'chuck-gen2',
  'chuck-gen2',
  'chuck',
  'chuck',
  'cilan',
  'cilan',
  'clair-gen2',
  'clair-gen2',
  'clair',
  'clair',
  'clay',
  'clay',
  'clemont',
  'clemont',
  'clerk-boss',
  'clerk-boss',
  'clerk',
  'clerk',
  'clerkf',
  'clerkf',
  'clown',
  'clown',
  'collector-gen3',
  'collector-gen3',
  'collector',
  'collector',
  'colress-gen7',
  'colress-gen7',
  'colress',
  'colress',
  'courtney-gen3',
  'courtney-gen3',
  'cowgirl',
  'cowgirl',
  'crasherwake',
  'crasherwake',
  'cress',
  'cress',
  'crushgirl-gen3',
  'crushgirl-gen3',
  'crushkin-gen3',
  'crushkin-gen3',
  'cueball-gen1',
  'cueball-gen1',
  'cueball-gen1rb',
  'cueball-gen1rb',
  'cueball-gen3',
  'cueball-gen3',
  'cyclist-gen4',
  'cyclist-gen4',
  'cyclist',
  'cyclist',
  'cyclistf-gen4',
  'cyclistf-gen4',
  'cyclistf',
  'cyclistf',
  'cynthia-gen4',
  'cynthia-gen4',
  'cynthia',
  'cynthia',
  'cyrus',
  'cyrus',
  'dahlia',
  'dahlia',
  'dancer',
  'dancer',
  'darach',
  'darach',
  'dawn-gen4pt',
  'dawn-gen4pt',
  'dawn',
  'dawn',
  'depotagent',
  'depotagent',
  'dexio',
  'dexio',
  'doctor',
  'doctor',
  'doubleteam',
  'doubleteam',
  'dragontamer-gen3',
  'dragontamer-gen3',
  'dragontamer',
  'dragontamer',
  'drake-gen3',
  'drake-gen3',
  'drasna',
  'drasna',
  'drayden',
  'drayden',
  'elesa-gen5bw2',
  'elesa-gen5bw2',
  'elesa',
  'elesa',
  'elio',
  'elio',
  'emmet',
  'emmet',
  'engineer-gen1',
  'engineer-gen1',
  'engineer-gen1rb',
  'engineer-gen1rb',
  'engineer-gen3',
  'engineer-gen3',
  'erika-gen1',
  'erika-gen1',
  'erika-gen1rb',
  'erika-gen1rb',
  'erika-gen2',
  'erika-gen2',
  'erika-gen3',
  'erika-gen3',
  'erika',
  'erika',
  'ethan-gen2',
  'ethan-gen2',
  'ethan-gen2c',
  'ethan-gen2c',
  'ethan',
  'ethan',
  'eusine-gen2',
  'eusine-gen2',
  'eusine',
  'eusine',
  'evelyn',
  'evelyn',
  'expert-gen3',
  'expert-gen3',
  'expertf-gen3',
  'expertf-gen3',
  'faba',
  'faba',
  'falkner-gen2',
  'falkner-gen2',
  'falkner',
  'falkner',
  'fantina',
  'fantina',
  'firebreather-gen2',
  'firebreather-gen2',
  'firebreather',
  'firebreather',
  'fisherman-gen1',
  'fisherman-gen1',
  'fisherman-gen1rb',
  'fisherman-gen1rb',
  'fisherman-gen2jp',
  'fisherman-gen2jp',
  'fisherman-gen3',
  'fisherman-gen3',
  'fisherman-gen3rs',
  'fisherman-gen3rs',
  'fisherman-gen4',
  'fisherman-gen4',
  'fisherman',
  'fisherman',
  'flannery-gen3',
  'flannery-gen3',
  'flannery',
  'flannery',
  'flint',
  'flint',
  'furisodegirl-black',
  'furisodegirl-black',
  'furisodegirl-pink',
  'furisodegirl-pink',
  'galacticgrunt',
  'galacticgrunt',
  'galacticgruntf',
  'galacticgruntf',
  'gambler-gen1',
  'gambler-gen1',
  'gambler-gen1rb',
  'gambler-gen1rb',
  'gambler',
  'gambler',
  'gamer-gen3',
  'gamer-gen3',
  'gardenia',
  'gardenia',
  'gentleman-gen1',
  'gentleman-gen1',
  'gentleman-gen1rb',
  'gentleman-gen1rb',
  'gentleman-gen2',
  'gentleman-gen2',
  'gentleman-gen3',
  'gentleman-gen3',
  'gentleman-gen3rs',
  'gentleman-gen3rs',
  'gentleman-gen4',
  'gentleman-gen4',
  'gentleman-gen4dp',
  'gentleman-gen4dp',
  'gentleman',
  'gentleman',
  'ghetsis-gen5bw',
  'ghetsis-gen5bw',
  'ghetsis',
  'ghetsis',
  'giovanni-gen1',
  'giovanni-gen1',
  'giovanni-gen1rb',
  'giovanni-gen1rb',
  'giovanni-gen3',
  'giovanni-gen3',
  'giovanni',
  'giovanni',
  'glacia-gen3',
  'glacia-gen3',
  'gladion-stance',
  'gladion-stance',
  'gladion',
  'gladion',
  'greta-gen3',
  'greta-gen3',
  'grimsley-gen7',
  'grimsley-gen7',
  'grimsley',
  'grimsley',
  'guitarist-gen3',
  'guitarist-gen3',
  'guitarist-gen4',
  'guitarist-gen4',
  'guitarist',
  'guitarist',
  'guzma',
  'guzma',
  'hala',
  'hala',
  'hapu',
  'hapu',
  'harlequin',
  'harlequin',
  'hau-stance',
  'hau-stance',
  'hau',
  'hau',
  'hexmaniac-gen3',
  'hexmaniac-gen3',
  'hexmaniac-gen3jp',
  'hexmaniac-gen3jp',
  'hiker-gen1',
  'hiker-gen1',
  'hiker-gen1rb',
  'hiker-gen1rb',
  'hiker-gen2',
  'hiker-gen2',
  'hiker-gen3',
  'hiker-gen3',
  'hiker-gen3rs',
  'hiker-gen3rs',
  'hiker-gen4',
  'hiker-gen4',
  'hiker-gen7',
  'hiker-gen7',
  'hiker',
  'hiker',
  'hilbert-dueldisk',
  'hilbert-dueldisk',
  'hilbert',
  'hilbert',
  'hilda-dueldisk',
  'hilda-dueldisk',
  'hilda',
  'hilda',
  'hooligans',
  'hooligans',
  'hoopster',
  'hoopster',
  'hugh',
  'hugh',
  'idol',
  'idol',
  'ilima',
  'ilima',
  'infielder',
  'infielder',
  'ingo',
  'ingo',
  'interviewers-gen3',
  'interviewers-gen3',
  'interviewers',
  'interviewers',
  'iris-gen5bw2',
  'iris-gen5bw2',
  'iris',
  'iris',
  'janine-gen2',
  'janine-gen2',
  'janine',
  'janine',
  'janitor',
  'janitor',
  'jasmine-gen2',
  'jasmine-gen2',
  'jasmine',
  'jasmine',
  'jessiejames-gen1',
  'jessiejames-gen1',
  'jogger',
  'jogger',
  'jrtrainer-gen1',
  'jrtrainer-gen1',
  'jrtrainer-gen1rb',
  'jrtrainer-gen1rb',
  'jrtrainerf-gen1',
  'jrtrainerf-gen1',
  'jrtrainerf-gen1rb',
  'jrtrainerf-gen1rb',
  'juan-gen3',
  'juan-gen3',
  'juan',
  'juan',
  'juggler-gen1',
  'juggler-gen1',
  'juggler-gen1rb',
  'juggler-gen1rb',
  'juggler-gen2',
  'juggler-gen2',
  'juggler-gen3',
  'juggler-gen3',
  'juggler',
  'juggler',
  'juniper',
  'juniper',
  'jupiter',
  'jupiter',
  'kahili',
  'kahili',
  'karen-gen2',
  'karen-gen2',
  'karen',
  'karen',
  'kiawe',
  'kiawe',
  'kimonogirl-gen2',
  'kimonogirl-gen2',
  'kimonogirl',
  'kimonogirl',
  'kindler-gen3',
  'kindler-gen3',
  'koga-gen1',
  'koga-gen1',
  'koga-gen1rb',
  'koga-gen1rb',
  'koga-gen2',
  'koga-gen2',
  'koga-gen3',
  'koga-gen3',
  'koga',
  'koga',
  'korrina',
  'korrina',
  'kris-gen2',
  'kris-gen2',
  'kukui-stand',
  'kukui-stand',
  'kukui',
  'kukui',
  'lady-gen3',
  'lady-gen3',
  'lady-gen3rs',
  'lady-gen3rs',
  'lady-gen4',
  'lady-gen4',
  'lady',
  'lady',
  'lana',
  'lana',
  'lance-gen1',
  'lance-gen1',
  'lance-gen1rb',
  'lance-gen1rb',
  'lance-gen2',
  'lance-gen2',
  'lance-gen3',
  'lance-gen3',
  'lance',
  'lance',
  'lass-gen1',
  'lass-gen1',
  'lass-gen1rb',
  'lass-gen1rb',
  'lass-gen2',
  'lass-gen2',
  'lass-gen3',
  'lass-gen3',
  'lass-gen3rs',
  'lass-gen3rs',
  'lass-gen4',
  'lass-gen4',
  'lass-gen4dp',
  'lass-gen4dp',
  'lass-gen7',
  'lass-gen7',
  'lass',
  'lass',
  'leaf-gen3',
  'leaf-gen3',
  'lenora',
  'lenora',
  'li',
  'li',
  'lillie-z',
  'lillie-z',
  'lillie',
  'lillie',
  'linebacker',
  'linebacker',
  'liza',
  'liza',
  'lorelei-gen1',
  'lorelei-gen1',
  'lorelei-gen1rb',
  'lorelei-gen1rb',
  'lorelei-gen3',
  'lorelei-gen3',
  'ltsurge-gen1',
  'ltsurge-gen1',
  'ltsurge-gen1rb',
  'ltsurge-gen1rb',
  'ltsurge-gen2',
  'ltsurge-gen2',
  'ltsurge-gen3',
  'ltsurge-gen3',
  'ltsurge',
  'ltsurge',
  'lucas-gen4pt',
  'lucas-gen4pt',
  'lucas',
  'lucas',
  'lucian',
  'lucian',
  'lucy-gen3',
  'lucy-gen3',
  'lusamine-nihilego',
  'lusamine-nihilego',
  'lusamine',
  'lusamine',
  'lyra',
  'lyra',
  'madame-gen4',
  'madame-gen4',
  'madame-gen4dp',
  'madame-gen4dp',
  'madame',
  'madame',
  'maid',
  'maid',
  'mallow',
  'mallow',
  'malva',
  'malva',
  'marley',
  'marley',
  'marlon',
  'marlon',
  'mars',
  'mars',
  'marshal',
  'marshal',
  'matt-gen3',
  'matt-gen3',
  'maxie-gen3',
  'maxie-gen3',
  'may-gen3',
  'may-gen3',
  'may-gen3rs',
  'may-gen3rs',
  'maylene',
  'maylene',
  'medium-gen2jp',
  'medium-gen2jp',
  'medium',
  'medium',
  'mina',
  'mina',
  'mira',
  'mira',
  'misty-gen1',
  'misty-gen1',
  'misty-gen1rb',
  'misty-gen1rb',
  'misty-gen2',
  'misty-gen2',
  'misty-gen3',
  'misty-gen3',
  'misty',
  'misty',
  'molayne',
  'molayne',
  'morty-gen2',
  'morty-gen2',
  'morty',
  'morty',
  'mrfuji-gen3',
  'mrfuji-gen3',
  'musician',
  'musician',
  'n',
  'n',
  'nanu',
  'nanu',
  'nate-dueldisk',
  'nate-dueldisk',
  'nate',
  'nate',
  'ninjaboy-gen3',
  'ninjaboy-gen3',
  'ninjaboy',
  'ninjaboy',
  'nita',
  'nita',
  'noland-gen3',
  'noland-gen3',
  'norman-gen3',
  'norman-gen3',
  'norman',
  'norman',
  'nurse',
  'nurse',
  'nurseryaide',
  'nurseryaide',
  'oak-gen1',
  'oak-gen1',
  'oak-gen1rb',
  'oak-gen1rb',
  'oak-gen2',
  'oak-gen2',
  'oak-gen3',
  'oak-gen3',
  'officer-gen2',
  'officer-gen2',
  'officeworker',
  'officeworker',
  'oldcouple-gen3',
  'oldcouple-gen3',
  'olivia',
  'olivia',
  'olympia',
  'olympia',
  'painter-gen3',
  'painter-gen3',
  'palmer',
  'palmer',
  'parasollady-gen3',
  'parasollady-gen3',
  'parasollady-gen4',
  'parasollady-gen4',
  'parasollady',
  'parasollady',
  'petrel',
  'petrel',
  'phoebe-gen3',
  'phoebe-gen3',
  'picnicker-gen2',
  'picnicker-gen2',
  'picnicker-gen3',
  'picnicker-gen3',
  'picnicker-gen3rs',
  'picnicker-gen3rs',
  'picnicker',
  'picnicker',
  'pilot',
  'pilot',
  'plasmagrunt-gen5bw',
  'plasmagrunt-gen5bw',
  'plasmagrunt',
  'plasmagrunt',
  'plasmagruntf-gen5bw',
  'plasmagruntf-gen5bw',
  'plasmagruntf',
  'plasmagruntf',
  'plumeria',
  'plumeria',
  'pokefan-gen2',
  'pokefan-gen2',
  'pokefan-gen3',
  'pokefan-gen3',
  'pokefan-gen4',
  'pokefan-gen4',
  'pokefan',
  'pokefan',
  'pokefanf-gen2',
  'pokefanf-gen2',
  'pokefanf-gen3',
  'pokefanf-gen3',
  'pokefanf-gen4',
  'pokefanf-gen4',
  'pokefanf',
  'pokefanf',
  'pokekid',
  'pokekid',
  'pokemaniac-gen1',
  'pokemaniac-gen1',
  'pokemaniac-gen1rb',
  'pokemaniac-gen1rb',
  'pokemaniac-gen3',
  'pokemaniac-gen3',
  'pokemaniac-gen3rs',
  'pokemaniac-gen3rs',
  'pokemaniac',
  'pokemaniac',
  'pokemonbreeder-gen3',
  'pokemonbreeder-gen3',
  'pokemonbreeder-gen4',
  'pokemonbreeder-gen4',
  'pokemonbreeder-gen7',
  'pokemonbreeder-gen7',
  'pokemonbreeder',
  'pokemonbreeder',
  'pokemonbreederf-gen3',
  'pokemonbreederf-gen3',
  'pokemonbreederf-gen3frlg',
  'pokemonbreederf-gen3frlg',
  'pokemonbreederf-gen4',
  'pokemonbreederf-gen4',
  'pokemonbreederf-gen7',
  'pokemonbreederf-gen7',
  'pokemonbreederf',
  'pokemonbreederf',
  'pokemonranger-gen3',
  'pokemonranger-gen3',
  'pokemonranger-gen3rs',
  'pokemonranger-gen3rs',
  'pokemonranger-gen4',
  'pokemonranger-gen4',
  'pokemonranger',
  'pokemonranger',
  'pokemonrangerf-gen3',
  'pokemonrangerf-gen3',
  'pokemonrangerf-gen3rs',
  'pokemonrangerf-gen3rs',
  'pokemonrangerf-gen4',
  'pokemonrangerf-gen4',
  'pokemonrangerf',
  'pokemonrangerf',
  'policeman-gen4',
  'policeman-gen4',
  'policeman',
  'policeman',
  'preschooler',
  'preschooler',
  'preschoolerf',
  'preschoolerf',
  'preschoolers',
  'preschoolers',
  'proton',
  'proton',
  'pryce-gen2',
  'pryce-gen2',
  'pryce',
  'pryce',
  'psychic-gen1',
  'psychic-gen1',
  'psychic-gen1rb',
  'psychic-gen1rb',
  'psychic-gen2',
  'psychic-gen2',
  'psychic-gen3',
  'psychic-gen3',
  'psychic-gen3rs',
  'psychic-gen3rs',
  'psychic-gen4',
  'psychic-gen4',
  'psychic',
  'psychic',
  'psychicf-gen3',
  'psychicf-gen3',
  'psychicf-gen3rs',
  'psychicf-gen3rs',
  'psychicf-gen4',
  'psychicf-gen4',
  'psychicf',
  'psychicf',
  'psychicfjp-gen3',
  'psychicfjp-gen3',
  'ramos',
  'ramos',
  'rancher',
  'rancher',
  'red-gen1',
  'red-gen1',
  'red-gen1main',
  'red-gen1main',
  'red-gen1rb',
  'red-gen1rb',
  'red-gen1title',
  'red-gen1title',
  'red-gen2',
  'red-gen2',
  'red-gen3',
  'red-gen3',
  'red-gen7',
  'red-gen7',
  'red',
  'red',
  'reporter',
  'reporter',
  'richboy-gen3',
  'richboy-gen3',
  'richboy-gen4',
  'richboy-gen4',
  'richboy',
  'richboy',
  'riley',
  'riley',
  'risingstar',
  'risingstar',
  'risingstarf',
  'risingstarf',
  'roark',
  'roark',
  'rocker-gen1',
  'rocker-gen1',
  'rocker-gen1rb',
  'rocker-gen1rb',
  'rocker-gen3',
  'rocker-gen3',
  'rocket-gen1',
  'rocket-gen1',
  'rocket-gen1rb',
  'rocket-gen1rb',
  'rocketexecutive-gen2',
  'rocketexecutive-gen2',
  'rocketexecutivef-gen2',
  'rocketexecutivef-gen2',
  'rocketgrunt-gen2',
  'rocketgrunt-gen2',
  'rocketgrunt',
  'rocketgrunt',
  'rocketgruntf-gen2',
  'rocketgruntf-gen2',
  'rocketgruntf',
  'rocketgruntf',
  'rood',
  'rood',
  'rosa-dueldisk',
  'rosa-dueldisk',
  'rosa',
  'rosa',
  'roughneck-gen4',
  'roughneck-gen4',
  'roughneck',
  'roughneck',
  'roxanne-gen3',
  'roxanne-gen3',
  'roxanne',
  'roxanne',
  'roxie',
  'roxie',
  'ruinmaniac-gen3',
  'ruinmaniac-gen3',
  'ruinmaniac-gen3rs',
  'ruinmaniac-gen3rs',
  'ruinmaniac',
  'ruinmaniac',
  'ryuki',
  'ryuki',
  'sabrina-gen1',
  'sabrina-gen1',
  'sabrina-gen1rb',
  'sabrina-gen1rb',
  'sabrina-gen2',
  'sabrina-gen2',
  'sabrina-gen3',
  'sabrina-gen3',
  'sabrina',
  'sabrina',
  'sage-gen2',
  'sage-gen2',
  'sage-gen2jp',
  'sage-gen2jp',
  'sage',
  'sage',
  'sailor-gen1',
  'sailor-gen1',
  'sailor-gen1rb',
  'sailor-gen1rb',
  'sailor-gen2',
  'sailor-gen2',
  'sailor-gen3',
  'sailor-gen3',
  'sailor-gen3jp',
  'sailor-gen3jp',
  'sailor-gen3rs',
  'sailor-gen3rs',
  'sailor',
  'sailor',
  'samsonoak',
  'samsonoak',
  'saturn',
  'saturn',
  'schoolboy-gen2',
  'schoolboy-gen2',
  'schoolkid-gen3',
  'schoolkid-gen3',
  'schoolkid-gen4',
  'schoolkid-gen4',
  'schoolkid-gen4dp',
  'schoolkid-gen4dp',
  'schoolkid',
  'schoolkid',
  'schoolkidf-gen3',
  'schoolkidf-gen3',
  'schoolkidf-gen4',
  'schoolkidf-gen4',
  'schoolkidf',
  'schoolkidf',
  'scientist-gen1',
  'scientist-gen1',
  'scientist-gen1rb',
  'scientist-gen1rb',
  'scientist-gen2',
  'scientist-gen2',
  'scientist-gen3',
  'scientist-gen3',
  'scientist-gen4',
  'scientist-gen4',
  'scientist-gen4dp',
  'scientist-gen4dp',
  'scientist',
  'scientist',
  'scientistf',
  'scientistf',
  'selene',
  'selene',
  'shadowtriad',
  'shadowtriad',
  'shauntal',
  'shauntal',
  'shelly-gen3',
  'shelly-gen3',
  'shelly',
  'shelly',
  'sidney-gen3',
  'sidney-gen3',
  'sidney',
  'sidney',
  'siebold',
  'siebold',
  'sightseer',
  'sightseer',
  'silver-gen2',
  'silver-gen2',
  'silver-gen2kanto',
  'silver-gen2kanto',
  'silver',
  'silver',
  'sina',
  'sina',
  'sisandbro-gen3',
  'sisandbro-gen3',
  'sisandbro-gen3rs',
  'sisandbro-gen3rs',
  'sisandbro',
  'sisandbro',
  'skier-gen2',
  'skier-gen2',
  'skier',
  'skier',
  'skierf-gen4dp',
  'skierf-gen4dp',
  'skierf',
  'skierf',
  'skyla',
  'skyla',
  'smasher',
  'smasher',
  'sophocles',
  'sophocles',
  'spenser-gen3',
  'spenser-gen3',
  'srandjr-gen3',
  'srandjr-gen3',
  'steven-gen3',
  'steven-gen3',
  'steven',
  'steven',
  'striker',
  'striker',
  'supernerd-gen1',
  'supernerd-gen1',
  'supernerd-gen1rb',
  'supernerd-gen1rb',
  'supernerd-gen2',
  'supernerd-gen2',
  'supernerd-gen3',
  'supernerd-gen3',
  'supernerd',
  'supernerd',
  'swimmer-gen1',
  'swimmer-gen1',
  'swimmer-gen1rb',
  'swimmer-gen1rb',
  'swimmer-gen4',
  'swimmer-gen4',
  'swimmer-gen4dp',
  'swimmer-gen4dp',
  'swimmer',
  'swimmer',
  'swimmerf-gen2',
  'swimmerf-gen2',
  'swimmerf-gen3',
  'swimmerf-gen3',
  'swimmerf-gen3rs',
  'swimmerf-gen3rs',
  'swimmerf-gen4',
  'swimmerf-gen4',
  'swimmerf-gen4dp',
  'swimmerf-gen4dp',
  'swimmerf',
  'swimmerf',
  'swimmerfjp-gen2',
  'swimmerfjp-gen2',
  'swimmerm-gen2',
  'swimmerm-gen2',
  'swimmerm-gen3',
  'swimmerm-gen3',
  'swimmerm-gen3rs',
  'swimmerm-gen3rs',
  'tabitha-gen3',
  'tabitha-gen3',
  'tamer-gen1',
  'tamer-gen1',
  'tamer-gen1rb',
  'tamer-gen1rb',
  'tamer-gen3',
  'tamer-gen3',
  'tate',
  'tate',
  'tateandliza-gen3',
  'tateandliza-gen3',
  'teacher-gen2',
  'teacher-gen2',
  'teacher-gen7',
  'teacher-gen7',
  'teacher',
  'teacher',
  'teamaquabeta-gen3',
  'teamaquabeta-gen3',
  'teamaquagruntf-gen3',
  'teamaquagruntf-gen3',
  'teamaquagruntm-gen3',
  'teamaquagruntm-gen3',
  'teammagmagruntf-gen3',
  'teammagmagruntf-gen3',
  'teammagmagruntm-gen3',
  'teammagmagruntm-gen3',
  'teamrocket',
  'teamrocket',
  'teamrocketgruntf-gen3',
  'teamrocketgruntf-gen3',
  'teamrocketgruntm-gen3',
  'teamrocketgruntm-gen3',
  'theroyal',
  'theroyal',
  'thorton',
  'thorton',
  'tierno',
  'tierno',
  'triathletebikerf-gen3',
  'triathletebikerf-gen3',
  'triathletebikerm-gen3',
  'triathletebikerm-gen3',
  'triathleterunnerf-gen3',
  'triathleterunnerf-gen3',
  'triathleterunnerm-gen3',
  'triathleterunnerm-gen3',
  'triathleteswimmerf-gen3',
  'triathleteswimmerf-gen3',
  'triathleteswimmerm-gen3',
  'triathleteswimmerm-gen3',
  'tuber-gen3',
  'tuber-gen3',
  'tuber',
  'tuber',
  'tuberf-gen3',
  'tuberf-gen3',
  'tuberf-gen3rs',
  'tuberf-gen3rs',
  'tuberf',
  'tuberf',
  'tucker-gen3',
  'tucker-gen3',
  'twins-gen2',
  'twins-gen2',
  'twins-gen3',
  'twins-gen3',
  'twins-gen3rs',
  'twins-gen3rs',
  'twins-gen4',
  'twins-gen4',
  'twins-gen4dp',
  'twins-gen4dp',
  'twins',
  'twins',
  'unknown',
  'unknown',
  'unknownf',
  'unknownf',
  'valerie',
  'valerie',
  'veteran-gen4',
  'veteran-gen4',
  'veteran',
  'veteran',
  'veteranf',
  'veteranf',
  'viola',
  'viola',
  'volkner',
  'volkner',
  'waiter-gen4',
  'waiter-gen4',
  'waiter-gen4dp',
  'waiter-gen4dp',
  'waiter',
  'waiter',
  'waitress-gen4',
  'waitress-gen4',
  'waitress',
  'waitress',
  'wallace-gen3',
  'wallace-gen3',
  'wallace-gen3rs',
  'wallace-gen3rs',
  'wallace-gen6',
  'wallace-gen6',
  'wallace',
  'wallace',
  'wally-gen3',
  'wally-gen3',
  'wally',
  'wally',
  'wattson-gen3',
  'wattson-gen3',
  'wattson',
  'wattson',
  'whitney-gen2',
  'whitney-gen2',
  'whitney',
  'whitney',
  'wicke',
  'wicke',
  'wikstrom',
  'wikstrom',
  'will-gen2',
  'will-gen2',
  'will',
  'will',
  'winona-gen3',
  'winona-gen3',
  'winona-gen6',
  'winona-gen6',
  'winona',
  'winona',
  'worker-gen4',
  'worker-gen4',
  'worker',
  'worker',
  'workerice',
  'workerice',
  'wulfric',
  'wulfric',
  'xerosic',
  'xerosic',
  'yellow',
  'yellow',
  'youngathlete',
  'youngathlete',
  'youngathletef',
  'youngathletef',
  'youngcouple-gen3',
  'youngcouple-gen3',
  'youngcouple-gen3rs',
  'youngcouple-gen3rs',
  'youngcouple-gen4dp',
  'youngcouple-gen4dp',
  'youngcouple',
  'youngcouple',
  'youngn',
  'youngn',
  'youngster-gen1',
  'youngster-gen1',
  'youngster-gen1rb',
  'youngster-gen1rb',
  'youngster-gen2',
  'youngster-gen2',
  'youngster-gen3',
  'youngster-gen3',
  'youngster-gen3rs',
  'youngster-gen3rs',
  'youngster-gen4',
  'youngster-gen4',
  'youngster-gen7',
  'youngster-gen7',
  'youngster',
  'youngster',
  'zinnia',
  'zinnia',
  'zinzolin',
  'zinzolin'
];

const Map<String, int> BattlePokemonIconIndexes = {
  'egg': 900 + 1,
  'pikachubelle': 900 + 2,
  'pikachulibre': 900 + 3,
  'pikachuphd': 900 + 4,
  'pikachupopstar': 900 + 5,
  'pikachurockstar': 900 + 6,
  'pikachucosplay': 900 + 7,
  'unownexclamation': 900 + 8,
  'unownquestion': 900 + 9,
  'unownb': 900 + 10,
  'unownc': 900 + 11,
  'unownd': 900 + 12,
  'unowne': 900 + 13,
  'unownf': 900 + 14,
  'unowng': 900 + 15,
  'unownh': 900 + 16,
  'unowni': 900 + 17,
  'unownj': 900 + 18,
  'unownk': 900 + 19,
  'unownl': 900 + 20,
  'unownm': 900 + 21,
  'unownn': 900 + 22,
  'unowno': 900 + 23,
  'unownp': 900 + 24,
  'unownq': 900 + 25,
  'unownr': 900 + 26,
  'unowns': 900 + 27,
  'unownt': 900 + 28,
  'unownu': 900 + 29,
  'unownv': 900 + 30,
  'unownw': 900 + 31,
  'unownx': 900 + 32,
  'unowny': 900 + 33,
  'unownz': 900 + 34,
  'castformrainy': 900 + 35,
  'castformsnowy': 900 + 36,
  'castformsunny': 900 + 37,
  'deoxysattack': 900 + 38,
  'deoxysdefense': 900 + 39,
  'deoxysspeed': 900 + 40,
  'burmysandy': 900 + 41,
  'burmytrash': 900 + 42,
  'wormadamsandy': 900 + 43,
  'wormadamtrash': 900 + 44,
  'cherrimsunshine': 900 + 45,
  'shelloseast': 900 + 46,
  'gastrodoneast': 900 + 47,
  'rotomfan': 900 + 48,
  'rotomfrost': 900 + 49,
  'rotomheat': 900 + 50,
  'rotommow': 900 + 51,
  'rotomwash': 900 + 52,
  'giratinaorigin': 900 + 53,
  'shayminsky': 900 + 54,
  'unfezantf': 900 + 55,
  'basculinbluestriped': 900 + 56,
  'darmanitanzen': 900 + 57,
  'deerlingautumn': 900 + 58,
  'deerlingsummer': 900 + 59,
  'deerlingwinter': 900 + 60,
  'sawsbuckautumn': 900 + 61,
  'sawsbucksummer': 900 + 62,
  'sawsbuckwinter': 900 + 63,
  'frillishf': 900 + 64,
  'jellicentf': 900 + 65,
  'tornadustherian': 900 + 66,
  'thundurustherian': 900 + 67,
  'landorustherian': 900 + 68,
  'kyuremblack': 900 + 69,
  'kyuremwhite': 900 + 70,
  'keldeoresolute': 900 + 71,
  'meloettapirouette': 900 + 72,
  'vivillonarchipelago': 900 + 73,
  'vivilloncontinental': 900 + 74,
  'vivillonelegant': 900 + 75,
  'vivillonfancy': 900 + 76,
  'vivillongarden': 900 + 77,
  'vivillonhighplains': 900 + 78,
  'vivillonicysnow': 900 + 79,
  'vivillonjungle': 900 + 80,
  'vivillonmarine': 900 + 81,
  'vivillonmodern': 900 + 82,
  'vivillonmonsoon': 900 + 83,
  'vivillonocean': 900 + 84,
  'vivillonpokeball': 900 + 85,
  'vivillonpolar': 900 + 86,
  'vivillonriver': 900 + 87,
  'vivillonsandstorm': 900 + 88,
  'vivillonsavanna': 900 + 89,
  'vivillonsun': 900 + 90,
  'vivillontundra': 900 + 91,
  'pyroarf': 900 + 92,
  'flabebeblue': 900 + 93,
  'flabebeorange': 900 + 94,
  'flabebewhite': 900 + 95,
  'flabebeyellow': 900 + 96,
  'floetteblue': 900 + 97,
  'floetteeternal': 900 + 98,
  'floetteorange': 900 + 99,
  'floettewhite': 900 + 100,
  'floetteyellow': 900 + 101,
  'florgesblue': 900 + 102,
  'florgesorange': 900 + 103,
  'florgeswhite': 900 + 104,
  'florgesyellow': 900 + 105,
  'furfroudandy': 900 + 106,
  'furfroudebutante': 900 + 107,
  'furfroudiamond': 900 + 108,
  'furfrouheart': 900 + 109,
  'furfroukabuki': 900 + 110,
  'furfroulareine': 900 + 111,
  'furfroumatron': 900 + 112,
  'furfroupharaoh': 900 + 113,
  'furfroustar': 900 + 114,
  'meowsticf': 900 + 115,
  'aegislashblade': 900 + 116,
  'hoopaunbound': 900 + 118,
  'rattataalola': 900 + 119,
  'raticatealola': 900 + 120,
  'raichualola': 900 + 121,
  'sandshrewalola': 900 + 122,
  'sandslashalola': 900 + 123,
  'vulpixalola': 900 + 124,
  'ninetalesalola': 900 + 125,
  'diglettalola': 900 + 126,
  'dugtrioalola': 900 + 127,
  'meowthalola': 900 + 128,
  'persianalola': 900 + 129,
  'geodudealola': 900 + 130,
  'graveleralola': 900 + 131,
  'golemalola': 900 + 132,
  'grimeralola': 900 + 133,
  'mukalola': 900 + 134,
  'exeggutoralola': 900 + 135,
  'marowakalola': 900 + 136,
  'greninjaash': 900 + 137,
  'zygarde10': 900 + 138,
  'zygardecomplete': 900 + 139,
  'oricoriopompom': 900 + 140,
  'oricoriopau': 900 + 141,
  'oricoriosensu': 900 + 142,
  'lycanrocmidnight': 900 + 143,
  'wishiwashischool': 900 + 144,
  'miniormeteor': 900 + 145,
  'miniororange': 900 + 146,
  'minioryellow': 900 + 147,
  'miniorgreen': 900 + 148,
  'miniorblue': 900 + 149,
  'miniorindigo': 900 + 150,
  'miniorviolet': 900 + 151,
  'magearnaoriginal': 900 + 152,
  'pikachuoriginal': 900 + 153,
  'pikachuhoenn': 900 + 154,
  'pikachusinnoh': 900 + 155,
  'pikachuunova': 900 + 156,
  'pikachukalos': 900 + 157,
  'pikachualola': 900 + 158,
  'pikachupartner': 900 + 159,
  'lycanrocdusk': 900 + 160,
  'necrozmaduskmane': 900 + 161,
  'necrozmadawnwings': 900 + 162,
  'necrozmaultra': 900 + 163,
  'pikachustarter': 900 + 164,
  'eeveestarter': 900 + 165,
  'meowthgalar': 900 + 166,
  'ponytagalar': 900 + 167,
  'rapidashgalar': 900 + 168,
  'farfetchdgalar': 900 + 169,
  'weezinggalar': 900 + 170,
  'mrmimegalar': 900 + 171,
  'corsolagalar': 900 + 172,
  'zigzagoongalar': 900 + 173,
  'linoonegalar': 900 + 174,
  'darumakagalar': 900 + 175,
  'darmanitangalar': 900 + 176,
  'darmanitangalarzen': 900 + 177,
  'yamaskgalar': 900 + 178,
  'stunfiskgalar': 900 + 179,
  'cramorantgulping': 900 + 180,
  'cramorantgorging': 900 + 181,
  'toxtricitylowkey': 900 + 182,
  'sinisteaantique': 854,
  'polteageistantique': 855,
  'alcremierubycream': 900 + 183,
  'alcremiematchacream': 900 + 184,
  'alcremiemintcream': 900 + 185,
  'alcremielemoncream': 900 + 186,
  'alcremiesaltedcream': 900 + 187,
  'alcremierubyswirl': 900 + 188,
  'alcremiecaramelswirl': 900 + 189,
  'alcremierainbowswirl': 900 + 190,
  'eiscuenoice': 900 + 191,
  'indeedeef': 900 + 192,
  'morpekohangry': 900 + 193,
  'zaciancrowned': 900 + 194,
  'zamazentacrowned': 900 + 195,
  'slowpokegalar': 900 + 196,
  'slowbrogalar': 900 + 197,
  'zarudedada': 900 + 198,
  'pikachuworld': 900 + 199,

  'gumshoostotem': 735,
  'raticatealolatotem': 900 + 120,
  'marowakalolatotem': 900 + 136,
  'araquanidtotem': 752,
  'lurantistotem': 754,
  'salazzletotem': 758,
  'vikavolttotem': 738,
  'togedemarutotem': 777,
  'mimikyutotem': 778,
  'mimikyubustedtotem': 778,
  'ribombeetotem': 743,
  'kommoototem': 784,

  'venusaurmega': 1104 + 0,
  'charizardmegax': 1104 + 1,
  'charizardmegay': 1104 + 2,
  'blastoisemega': 1104 + 3,
  'beedrillmega': 1104 + 4,
  'pidgeotmega': 1104 + 5,
  'alakazammega': 1104 + 6,
  'slowbromega': 1104 + 7,
  'gengarmega': 1104 + 8,
  'kangaskhanmega': 1104 + 9,
  'pinsirmega': 1104 + 10,
  'gyaradosmega': 1104 + 11,
  'aerodactylmega': 1104 + 12,
  'mewtwomegax': 1104 + 13,
  'mewtwomegay': 1104 + 14,
  'ampharosmega': 1104 + 15,
  'steelixmega': 1104 + 16,
  'scizormega': 1104 + 17,
  'heracrossmega': 1104 + 18,
  'houndoommega': 1104 + 19,
  'tyranitarmega': 1104 + 20,
  'sceptilemega': 1104 + 21,
  'blazikenmega': 1104 + 22,
  'swampertmega': 1104 + 23,
  'gardevoirmega': 1104 + 24,
  'sableyemega': 1104 + 25,
  'mawilemega': 1104 + 26,
  'aggronmega': 1104 + 27,
  'medichammega': 1104 + 28,
  'manectricmega': 1104 + 29,
  'sharpedomega': 1104 + 30,
  'cameruptmega': 1104 + 31,
  'altariamega': 1104 + 32,
  'banettemega': 1104 + 33,
  'absolmega': 1104 + 34,
  'glaliemega': 1104 + 35,
  'salamencemega': 1104 + 36,
  'metagrossmega': 1104 + 37,
  'latiasmega': 1104 + 38,
  'latiosmega': 1104 + 39,
  'kyogreprimal': 1104 + 40,
  'groudonprimal': 1104 + 41,
  'rayquazamega': 1104 + 42,
  'lopunnymega': 1104 + 43,
  'garchompmega': 1104 + 44,
  'lucariomega': 1104 + 45,
  'abomasnowmega': 1104 + 46,
  'gallademega': 1104 + 47,
  'audinomega': 1104 + 48,
  'dianciemega': 1104 + 49,
  'charizardgmax': 1104 + 50,
  'butterfreegmax': 1104 + 51,
  'pikachugmax': 1104 + 52,
  'meowthgmax': 1104 + 53,
  'machampgmax': 1104 + 54,
  'gengargmax': 1104 + 55,
  'kinglergmax': 1104 + 56,
  'laprasgmax': 1104 + 57,
  'eeveegmax': 1104 + 58,
  'snorlaxgmax': 1104 + 59,
  'garbodorgmax': 1104 + 60,
  'melmetalgmax': 1104 + 61,
  'corviknightgmax': 1104 + 62,
  'orbeetlegmax': 1104 + 63,
  'drednawgmax': 1104 + 64,
  'coalossalgmax': 1104 + 65,
  'flapplegmax': 1104 + 66,
  'appletungmax': 1104 + 67,
  'sandacondagmax': 1104 + 68,
  'toxtricitygmax': 1104 + 69,
  'toxtricitylowkeygmax': 1104 + 69,
  'centiskorchgmax': 1104 + 70,
  'hatterenegmax': 1104 + 71,
  'grimmsnarlgmax': 1104 + 72,
  'alcremiegmax': 1104 + 73,
  'copperajahgmax': 1104 + 74,
  'duraludongmax': 1104 + 75,
  'eternatuseternamax': 1104 + 76,
  'venusaurgmax': 1104 + 77,
  'blastoisegmax': 1104 + 78,
  'rillaboomgmax': 1104 + 79,
  'cinderacegmax': 1104 + 80,
  'inteleongmax': 1104 + 81,
  'urshifugmax': 1104 + 82,
  'urshifurapidstrikegmax': 1104 + 83,

  'syclant': 1296 + 0,
  'revenankh': 1296 + 1,
  'pyroak': 1296 + 2,
  'fidgit': 1296 + 3,
  'stratagem': 1296 + 4,
  'arghonaut': 1296 + 5,
  'kitsunoh': 1296 + 6,
  'cyclohm': 1296 + 7,
  'colossoil': 1296 + 8,
  'krilowatt': 1296 + 9,
  'voodoom': 1296 + 10,
  'tomohawk': 1296 + 11,
  'necturna': 1296 + 12,
  'mollux': 1296 + 13,
  'aurumoth': 1296 + 14,
  'malaconda': 1296 + 15,
  'cawmodore': 1296 + 16,
  'volkraken': 1296 + 17,
  'plasmanta': 1296 + 18,
  'naviathan': 1296 + 19,
  'crucibelle': 1296 + 20,
  'crucibellemega': 1296 + 21,
  'kerfluffle': 1296 + 22,
  'pajantom': 1296 + 23,
  'jumbao': 1296 + 24,
  'caribolt': 1296 + 25,
  'smokomodo': 1296 + 26,
  'snaelstrom': 1296 + 27,
  'equilibra': 1296 + 28,
  'astrolotl': 1296 + 29,

  'syclar': 1332 + 0,
  'embirch': 1332 + 1,
  'flarelm': 1332 + 2,
  'breezi': 1332 + 3,
  'scratchet': 1332 + 4,
  'necturine': 1332 + 5,
  'cupra': 1332 + 6,
  'argalis': 1332 + 7,
  'brattler': 1332 + 8,
  'cawdet': 1332 + 9,
  'volkritter': 1332 + 10,
  'snugglow': 1332 + 11,
  'floatoy': 1332 + 12,
  'caimanoe': 1332 + 13,
  'pluffle': 1332 + 14,
  'rebble': 1332 + 15,
  'tactite': 1332 + 16,
  'privatyke': 1332 + 17,
  'nohface': 1332 + 18,
  'monohm': 1332 + 19,
  'duohm': 1332 + 20,
  //  protowatt: 1332 + 21,
  'voodoll': 1332 + 22,
  'mumbao': 1332 + 23,
  'fawnifer': 1332 + 24,
  'electrelk': 1332 + 25,
  'smogecko': 1332 + 26,
  'smoguana': 1332 + 27,
  'swirlpool': 1332 + 28,
  'coribalis': 1332 + 29,
  'justyke': 1332 + 30,
  'solotl': 1332 + 31,
};
